### PR TITLE
Setup IPC for spawned node process

### PR DESCRIPTION
**Pull request by geek**
* Allows sending messages to spawned node processes
* Setup fuge as preloader for spawned process

### CODE REVIEW

**Comment by geek** [comment]
@pelger this is ready

**Comment by geek** [comment]
@AdrianRossouw @pelger ready for the merge

**Comment by AdrianRossouw** [comment]
@geek i'm just a bit concerned this affects some of the changes I am making around environment variables at the moment.

I'm needing to add support for env_file's from the compose file, and this code seems to remove a bunch of the env stuff.

**Comment by AdrianRossouw** [comment]
actually. nm. it just moved the code around, didn't remove it outright.

I will merge in the next 2 days.

**Comment by geek** [comment]
@AdrianRossouw thanks.  The best part of the PR is the ability to recognize when you are running a node process vs other process

**Pull request merged**
